import { Shell, Unconnected, Mark } from "./Shell";
import styles from "./admin.module.css";

export function Campaigns() {
  return <Shell active="/admin/akcije" title="Popup / Akcije" intro="Važne poruke, u pravo vrijeme. Bez trajnog mijenjanja stranice."><Unconnected title="Prostor za buduće akcije">Upravljanje akcijama još nije povezano. Nijedna akcija nije kreirana ili aktivirana kroz administraciju.</Unconnected><section className={styles.emptyState}><Mark kind="campaign" /><h2>Poruka sa svojim početkom i krajem.</h2><p>Kurban, Bajram, upis i važne obavijesti imat će nacrt, jezičke verzije i period prikazivanja.</p><button className={styles.secondary} disabled>Nova akcija · uskoro</button></section><div className={styles.noticeInline}><p>Javni prikaz akcija i odnos s jezičkim uvodom bit će odobreni prije povezivanja.</p></div></Shell>;
}
export function ExamResults({ documentTitle, hasPdf }: { documentTitle: string; hasPdf: boolean }) {
  return <Shell active="/admin/rezultati" title="Rezultati ispita" intro="Jedan službeni dokument. Dostupan na sva tri jezika."><section className={styles.documentSection}><div><p className={styles.eyebrow}>Postojeća javna stranica</p><h2>{documentTitle}</h2><span className={styles.status}>{hasPdf ? "PDF je povezan" : "PDF još nije povezan"}</span><p>Objavljeni dokument kasnije će hraniti postojeći modul rezultata i stranicu upisa. Njihov izgled ostaje zaštićen.</p></div><div className={styles.uploadPlaceholder}><Mark kind="document" /><h3>Službeni PDF</h3><p>Prijenos datoteka čeka povezivanje sigurnog spremišta.</p><button className={styles.secondary} disabled>Odaberi PDF</button></div></section><Unconnected title="Objavljivanje dokumenata nije povezano">Buduća objava uključuje provjeru PDF-a, školske godine, BS/SQ/EN naslova i potvrdu administratora.</Unconnected></Shell>;
}
