import Link from "next/link";
import { Shell, Mark } from "./Shell";
import styles from "./admin.module.css";

export type ArchiveRow = { id: string; title: string; date: string; photos: number; slug: string };
export function Overview({ rows }: { rows: ArchiveRow[] }) {
  return <Shell active="/admin" title="Dobro došli u Medresu." intro="Sve što objavljujemo počinje pažljivim uređivanjem." action={<Link href="/admin/vijesti/nova" className={styles.primary}>＋ Nova vijest</Link>}>
    <section className={styles.overviewStrip} aria-label="Stanje sadržaja"><div><span>Javna arhiva</span><strong>{rows.length}<small>vijesti</small></strong><p>Postojeći sadržaj · sva 3 jezika</p></div><div><span>Urednički prostor</span><strong>BS <em>/</em> SQ <em>/</em> EN</strong><p>Jedna priča. Tri jezičke verzije.</p></div><div><span>Objavljivanje</span><strong className={styles.textMetric}>Čeka povezivanje</strong><p>Javna stranica ostaje zaštićena.</p></div></section>
    <div className={styles.dashboardColumns}><section><div className={styles.sectionHead}><h2>Posljednje javne vijesti</h2><Link href="/admin/vijesti">Otvori arhivu →</Link></div><ol className={styles.recent}>{rows.slice(0, 3).map((r, i) => <li key={r.id}><span className={styles.ordinal}>0{i + 1}</span><div><time dateTime={r.date}>{r.date}</time><h3>{r.title}</h3><span className={styles.status}>Objavljeno · javna arhiva</span></div><Link className={styles.arrowLink} href={`/admin/vijesti?preview=${r.id}`} aria-label={`Pregled: ${r.title}`}>↗</Link></li>)}</ol></section>
    <section className={styles.nextSteps}><p className={styles.eyebrow}>Pažljivo, korak po korak</p><h2>Od nacrta do objave.</h2><ol><li><b>01</b><span>Napišite bosansku verziju.<small>Tekst i slike, redoslijedom priče.</small></span></li><li><b>02</b><span>Pregledajte sva tri jezika.<small>Prijevod je nacrt, pregled je ljudski.</small></span></li><li><b>03</b><span>Objavite nakon provjere.<small>Jedna odobrena objava za BS, SQ i EN.</small></span></li></ol><p className={styles.muted}>Spremanje i objavljivanje bit će dostupni nakon povezivanja uredničke baze.</p></section></div>
    <section className={styles.quickLinks} aria-label="Ostali dijelovi administracije">{[{ href: "rezultati", title: "Rezultati ispita", text: "Službeni PDF, na postojećem mjestu.", icon: "document" }, { href: "akcije", title: "Popup / Akcije", text: "Privremene poruke, pažljivo planirane.", icon: "campaign" }, { href: "analitika", title: "Analitika", text: "Stvarni podaci kada se izvori povežu.", icon: "analytics" }].map(x => <Link key={x.href} href={`/admin/${x.href}`}><Mark kind={x.icon} /><div><h3>{x.title}</h3><p>{x.text}</p></div><span>↗</span></Link>)}</section>
  </Shell>;
}
